### ISSUE TITLE
Problem with XML format

### ISSUE THREAD

**Issue by roxfr** [mickaelbaron/jaxrs-tutorial#1]
=> Interrogation et réservation de billets de train

Hello,
The application does not work for output in XML format.
It seems to me that you have to use "GenericEntity" ?
Regards,
Roxfr

**XML**

![image](https://user-images.githubusercontent.com/52124613/206286318-38dd120e-a611-4f4f-a40f-c4d0c8665d62.png)

![image](https://user-images.githubusercontent.com/52124613/206286262-31e23592-a1f8-42bc-b42c-4f828ca8a776.png)

**JSON**

![image](https://user-images.githubusercontent.com/52124613/206286832-8bc379f6-8e29-48ad-859d-4c9266d447cd.png)

![image](https://user-images.githubusercontent.com/52124613/206286771-9d664e0a-59af-4047-acab-becdc3306bb9.png)

**Comment by mickaelbaron** [comment]
Hi,

Thank you for the interest in this tutorial

Can you ensure the Train class contains the @XmlRootElement annotation

```
@XmlRootElement(name = "train")
public class Train {
```

Can you check also the following Maven dependencies are declared into the pom.xml

```
	<dependencies>
		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-grizzly2-http</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-jaxb</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.media</groupId>
			<artifactId>jersey-media-json-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
	</dependencies>
```

Best

Mickael

**Comment by roxfr** [comment]
![image](https://user-images.githubusercontent.com/52124613/206295277-6d7cb5d9-99cf-4f54-acff-2323c52102e6.png)

My pom.xml file
I copied the file from => https://github.com/mickaelbaron/jaxrs-tutorial/blob/master/jaxrs-tutorial-exercice3/pom.xml

<project
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>soa.jaxrslabs</groupId>
	<artifactId>BookTrainRestWebServiceExercice3</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<properties>
		<jersey.version>3.0.2</jersey.version>
		<jaxb.version>3.0.1</jaxb.version>

		<maven.compiler.version>3.1</maven.compiler.version>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>

		<maven.dependency.version>3.1.1</maven.dependency.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.glassfish.jersey</groupId>
				<artifactId>jersey-bom</artifactId>
				<version>${jersey.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.glassfish.jersey.containers</groupId>
			<artifactId>jersey-container-grizzly2-http</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jersey.inject</groupId>
			<artifactId>jersey-hk2</artifactId>
		</dependency>
		<dependency>
        <groupId>org.glassfish.jersey.media</groupId>
	    <artifactId>jersey-media-jaxb</artifactId>
        </dependency>
        <dependency>
        <groupId>org.glassfish.jersey.media</groupId>
        <artifactId>jersey-media-json-jackson</artifactId>
        </dependency>
		<dependency>
			<groupId>jakarta.xml.bind</groupId>
			<artifactId>jakarta.xml.bind-api</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>${jaxb.version}</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven.compiler.version}</version>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
					<encoding>${project.build.sourceEncoding}</encoding>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by mickaelbaron** [comment]
Hi,

Can you send me your Maven project (pom.xml and src content)

Mickael

**Comment by roxfr** [comment]
Hi,

Here is the Maven :

![image](https://user-images.githubusercontent.com/52124613/206383739-e8e797ef-9d63-4a11-88b9-8769e974b83a.png)

and my src :

[src.zip](https://github.com/mickaelbaron/jaxrs-tutorial/files/10183044/src.zip)

Regards,
Roxfr

**Comment by mickaelbaron** [comment]
Please send me an archive with pom.xml file and the _src_ directory. In your previous archive, pom.xml was missing ...

**Comment by roxfr** [comment]
Here is the full project :

[Book.zip](https://github.com/mickaelbaron/jaxrs-tutorial/files/10183278/Book.zip)

Others ;
- Windows 11,
- Eclipse 2022-09,
-  jdk1.8.0_202.

**Comment by mickaelbaron** [comment]
Hi,

I solved your problem. Into the `Train` class, you have a bad class import.

In your code

```
import javax.xml.bind.annotation.XmlRootElement;
```
It should be 

```
import jakarta.xml.bind.annotation.XmlRootElement;
```

You need to impact also the `TrainBooking` class.

Best

**Comment by roxfr** [comment]
Good job 👍 
Thanks you !

![image](https://user-images.githubusercontent.com/52124613/206399776-5a5abc35-6153-44d4-a20e-595ceee3f27f.png)

![image](https://user-images.githubusercontent.com/52124613/206399852-c6ad200a-ebb5-4059-921c-0e55d6294091.png)

**Comment by mickaelbaron** [comment]
Cool 👍
